import assert from "node:assert/strict";
import { describe, it } from "node:test";
import {
  productBriefArtifactSchema,
  storyboardScriptVoiceoverLimit,
  validateP0StoryboardScript,
} from "@aigc-video/shared";
import { buildDeterministicStoryboard } from "./deterministic-artifacts.js";

describe("deterministic artifact builders", () => {
  it("builds storyboard voiceover from product brief instead of fixed copy", () => {
    const brief = productBriefArtifactSchema.parse({
      product: {
        name: "SwiftClean Mop",
        category: "home care",
        keyFacts: ["microfiber", "machine washable"],
        assets: [{ ref: "mop.png", useAs: "primary" }],
      },
      audience: {
        who: "busy renters",
        painOrDesire: "快速处理地面水渍",
      },
      coreSellingPoint: "三秒吸水不留痕",
      proof: ["加厚纤维现场吸干厨房水渍"],
      offer: "今天领券试用",
      platform: "Seedance",
      brandTone: "clean practical",
      bannedExpressions: [],
      landingInfo: null,
      assumptions: [],
    });

    const storyboard = buildDeterministicStoryboard(brief);
    const voiceovers = storyboard.shots.map((shot) => shot.voiceover);

    assert.deepEqual(storyboard.assumptions, [
      "Generated by deterministic storyboard builder.",
      "Storyboard generated from approved product brief.",
    ]);
    assert.equal(
      voiceovers.some((voiceover) => voiceover.includes("第一眼看清需求")),
      false,
    );
    assert.equal(
      voiceovers.some((voiceover) => voiceover.includes("核心卖点现场证明")),
      false,
    );
    assert.equal(
      voiceovers.some((voiceover) => voiceover.includes("现在就去了解")),
      false,
    );
    assert.match(voiceovers[0] ?? "", /快速处理地面水渍|SwiftClean/);
    assert.match(voiceovers[1] ?? "", /三秒吸水不留痕|加厚纤维/);
    assert.match(voiceovers[2] ?? "", /今天领券试用/);

    for (const shot of storyboard.shots) {
      assert.ok(
        Array.from(shot.voiceover).length <=
          storyboardScriptVoiceoverLimit(shot.durationSec),
      );
    }
    assert.equal(validateP0StoryboardScript(storyboard).valid, true);
  });
});
