import {
  productBriefArtifactSchema,
  storyboardArtifactSchema,
  storyboardScriptVoiceoverLimit,
  STORYBOARD_SCRIPT_DEFAULT_DURATIONS,
  STORYBOARD_SCRIPT_TOTAL_DURATION_SEC,
  type MaterialIntakeArtifact,
  type ProductBriefArtifact,
  type StoryboardArtifact,
} from "@aigc-video/shared";

function firstSellingPoint(input: string) {
  return (
    input
      .split(/[,\n，]/)
      .map((value) => value.trim())
      .find(Boolean) ?? input.trim()
  );
}

function inferProductName(input: {
  title?: string;
  userDirection?: string;
  material: MaterialIntakeArtifact;
  draft?: ProductBriefArtifact;
}) {
  return (
    input.draft?.product.name.trim() ||
    input.title?.trim() ||
    input.material.assets.find(
      (asset) => asset.ref === input.material.primaryProductRef,
    )?.description ||
    input.userDirection?.trim().slice(0, 48) ||
    "Imported product"
  );
}

function inferSellingPoint(input: {
  sellingPoints?: string;
  userDirection?: string;
  material: MaterialIntakeArtifact;
  draft?: ProductBriefArtifact;
}) {
  return (
    firstSellingPoint(input.sellingPoints ?? "") ||
    input.userDirection?.trim() ||
    input.draft?.coreSellingPoint.trim() ||
    input.material.assets.find((asset) => asset.included)?.description ||
    "Product benefit inferred from selected materials"
  );
}

export function buildDeterministicProductBrief(input: {
  userDirection?: string;
  title?: string;
  sellingPoints?: string;
  audience?: string;
  stylePreference?: string;
  material: MaterialIntakeArtifact;
  draft?: ProductBriefArtifact;
}): ProductBriefArtifact {
  const sellingPoint = inferSellingPoint(input);
  const productName = inferProductName(input);
  const audience =
    input.audience?.trim() ||
    input.draft?.audience.who.trim() ||
    "target ecommerce shoppers";
  const productAssets = input.material.assets
    .filter((asset) => asset.included && asset.kind === "image")
    .map((asset) => ({
      ref: asset.ref,
      useAs:
        asset.ref === input.material.primaryProductRef ? "primary" : "support",
    }));

  return productBriefArtifactSchema.parse({
    product: {
      name: productName,
      category: input.draft?.product.category ?? "consumer product",
      keyFacts: (input.sellingPoints ?? sellingPoint)
        .split(/[,\n，]/)
        .map((value) => value.trim())
        .filter(Boolean)
        .concat(input.draft?.product.keyFacts ?? []),
      assets: productAssets.length > 0
        ? productAssets
        : (input.draft?.product.assets ?? []),
    },
    audience: {
      who: audience,
      painOrDesire: input.draft?.audience.painOrDesire ?? `Needs ${sellingPoint}`,
    },
    coreSellingPoint: sellingPoint,
    proof: [
      ...(input.draft?.proof ?? []),
      ...input.material.assets
        .filter((asset) => asset.included)
        .map((asset) => asset.description),
    ],
    offer: input.draft?.offer ?? null,
    platform: input.draft?.platform ?? "Seedance",
    brandTone: input.stylePreference ?? input.draft?.brandTone ?? "clear ecommerce",
    bannedExpressions: input.draft?.bannedExpressions ?? [],
    landingInfo: input.draft?.landingInfo ?? null,
    assumptions: [
      ...(input.draft?.assumptions ?? []),
      "Generated by deterministic product brief builder.",
      input.draft
        ? "Regenerated from merchant direction and current product brief draft."
        : "Generated from approved material intake.",
    ],
  });
}

function primaryBriefAsset(brief: ProductBriefArtifact) {
  return (
    brief.product.assets.find((asset) => asset.useAs === "primary")?.ref ??
    brief.product.assets[0]?.ref ??
    "product"
  );
}

function clampVoiceover(value: string, durationSec: number) {
  const limit = storyboardScriptVoiceoverLimit(durationSec);
  const normalized = Array.from(value.replace(/\s+/g, ""));
  return normalized.slice(0, Math.max(1, limit)).join("");
}

export function buildDeterministicStoryboard(
  brief: ProductBriefArtifact,
): StoryboardArtifact {
  const productAssetRef = primaryBriefAsset(brief);
  const proof = brief.proof[0]?.trim() || brief.coreSellingPoint;
  const offer = brief.offer?.trim() || "查看详情";
  const durations = STORYBOARD_SCRIPT_DEFAULT_DURATIONS;

  return storyboardArtifactSchema.parse({
    narrative: `${brief.product.name} helps ${brief.audience.who} with ${brief.coreSellingPoint}.`,
    totalDurationSec: STORYBOARD_SCRIPT_TOTAL_DURATION_SEC,
    shots: [
      {
        index: 0,
        purpose: "hook",
        durationSec: durations[0],
        scene: `${brief.product.name} hero problem hook`,
        visualDirection: `Show ${productAssetRef} as the primary product asset with ${brief.brandTone} styling.`,
        productAssetRef,
        voiceover: clampVoiceover(
          `${brief.audience.painOrDesire}，先看${brief.product.name}`,
          durations[0],
        ),
        transition: "cut",
      },
      {
        index: 1,
        purpose: "proof",
        durationSec: durations[1],
        scene: `${brief.coreSellingPoint} selling point proof`,
        visualDirection: `Use ${productAssetRef} in a realistic moment and support it with: ${proof}.`,
        productAssetRef,
        voiceover: clampVoiceover(`${brief.coreSellingPoint}，${proof}`, durations[1]),
        transition: "match cut",
      },
      {
        index: 2,
        purpose: "cta",
        durationSec: durations[2],
        scene: `${offer} purchase call to action`,
        visualDirection: `End on ${productAssetRef} with a confident ecommerce packshot and ${offer}.`,
        productAssetRef,
        voiceover: clampVoiceover(`${offer}，马上看详情`, durations[2]),
        transition: "fade",
      },
    ],
    assumptions: [
      "Generated by deterministic storyboard builder.",
      "Storyboard generated from approved product brief.",
    ],
  });
}
